name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "* */30 * * *"
  push:
    branches:
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: wangrongding/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 1677e357a18931fc3f5868cd59057ff7
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@1.0.9
