name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/1 * * * *"
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: dde0a407006d7fdd5fb0345cd2fc1a6c
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LANGUAGE : True
          SHOW_OS : True
          SHOW_EDITORS : True